spring:
  security:
    user:
      password: 1
  h2:
    console:
      enabled: true
    datasource:
        url: jdbc:h2:mem:miniboard
        username: sa
        password:
        driver-class-name: org.h2.Driver
